package com.pazim.smsemailforwarder;
import android.app.PendingIntent; import android.content.*; import android.telephony.SmsManager; import java.io.*; import java.net.*; import java.nio.charset.StandardCharsets; import java.util.*; import java.util.concurrent.*;
public final class Forwarder { private static final ExecutorService E=Executors.newSingleThreadExecutor(); private Forwarder(){}
 public static void forward(Context c,String sender,String msg){boolean any=false;if(AppPrefs.email(c)){sendEmail(c,sender,msg);any=true;}if(AppPrefs.sms(c)){sendSms(c,sender,msg);any=true;}if(!any)HistoryStore.add(c,"SYSTEM","",sender,msg,"SKIPPED","Both switches are off.");}
 public static void sendEmail(Context c,String sender,String msg){String id=HistoryStore.add(c,"EMAIL","Apps Script relay",sender,msg,"SENDING","Connecting…");E.execute(()->{if(!Config.WEB_APP_URL.startsWith("https://")||!Config.WEB_APP_URL.endsWith("/exec")){HistoryStore.updateStatus(c,id,"FAILED","Config.java needs a deployed HTTPS /exec URL.");return;}HttpURLConnection h=null;try{h=(HttpURLConnection)new URL(Config.WEB_APP_URL).openConnection();h.setRequestMethod("POST");h.setConnectTimeout(15000);h.setReadTimeout(15000);h.setInstanceFollowRedirects(true);h.setDoOutput(true);h.setRequestProperty("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");String form="secret="+enc(Config.SHARED_SECRET)+"&sender="+enc(sender)+"&message="+enc(msg)+"&timestamp="+System.currentTimeMillis();byte[] data=form.getBytes(StandardCharsets.UTF_8);try(OutputStream o=h.getOutputStream()){o.write(data);}int code=h.getResponseCode();String r=read(code>=400?h.getErrorStream():h.getInputStream());if(code>=200&&code<400&&r.startsWith("OK"))HistoryStore.updateStatus(c,id,"SENT",r);else HistoryStore.updateStatus(c,id,"FAILED","HTTP "+code+" • "+r);}catch(Exception e){HistoryStore.updateStatus(c,id,"FAILED",e.getClass().getSimpleName()+": "+e.getMessage());}finally{if(h!=null)h.disconnect();}});}
 public static void sendSms(Context c,String sender,String msg){String dest=AppPrefs.phone(c);if(dest.isEmpty()){HistoryStore.add(c,"SMS","",sender,msg,"FAILED","Destination phone is empty.");return;}String id=HistoryStore.add(c,"SMS",dest,sender,msg,"SENDING","Submitted to Android SMS service.");try{SmsManager m=SmsManager.getDefault();ArrayList<String> parts=m.divideMessage("Forwarded SMS\nFrom: " + sender + "\n\n" + msg);ArrayList<PendingIntent> sent=new ArrayList<>();for(int n=0;n<parts.size();n++){Intent x=new Intent(c,SmsStatusReceiver.class);x.putExtra("id",id);x.putExtra("part",n);x.putExtra("count",parts.size());sent.add(PendingIntent.getBroadcast(c,(id+n).hashCode(),x,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE));}m.sendMultipartTextMessage(dest,null,parts,sent,null);}catch(Exception e){HistoryStore.updateStatus(c,id,"FAILED",e.getClass().getSimpleName()+": "+e.getMessage());}}
 private static String enc(String v)throws Exception{return URLEncoder.encode(v==null?"":v,StandardCharsets.UTF_8.name());}
 private static String read(InputStream in)throws Exception{if(in==null)return "(empty response)";BufferedReader br=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder b=new StringBuilder();String l;while((l=br.readLine())!=null)b.append(l);br.close();return b.toString().trim();}
}
